{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "aks-node-termination-handler.fullname" . }}
  labels:
    {{- include "aks-node-termination-handler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aks-node-termination-handler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "aks-node-termination-handler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}